slug: pvdomics
visit: visit
charts: 
- chart: pvdsleep
  title: PVDOMICS Study Type

webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://preview.sleepdata.org
